### ISSUE TITLE
박스오피스앱 STEP1 

### ISSUE THREAD

**Issue by happykwon** [happykwon/ios-box-office#1]
## Feature  Issue
연락처 관리 앱 STEP1 모델링 및  테이블뷰 초기 구현 

## Todo
- [x] MockJSON 데이터와 매핑할 모델 설계
- [x] CodingKeys 프로토콜의 활용
- [x] 단위 테스트(Unit Test)를 통한 모델 설계 검증
